# Generated by Django 5.2.6 on 2025-09-23 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='زبان')),
            ],
            options={
                'verbose_name': 'زبان',
                'verbose_name_plural': 'معرفی زبان',
            },
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=100, verbose_name='معنی')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meaning', to='dict.language', verbose_name='زبان')),
            ],
            options={
                'verbose_name': 'معنی',
                'verbose_name_plural': 'معانی',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='لغت')),
                ('meaning', models.ManyToManyField(blank=True, related_name='word', to='dict.meaning', verbose_name='معنی')),
            ],
            options={
                'verbose_name': 'لغت',
                'verbose_name_plural': 'لغات',
            },
        ),
    ]
