# Generated by Django 5.2.6 on 2025-09-30 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={},
        ),
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='dict.language', verbose_name='زبان'),
            preserve_default=False,
        ),
    ]
